Update cicd.yaml

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -62,19 +62,17 @@ jobs:
         kubectl rollout status deployment/$IMAGE --timeout=120s
 
     # Health Check + Auto Rollback
-    - name: Health Check and Rollback if Needed
+    - name: Health Check inside cluster
       run: |
-        echo "Waiting 30 seconds before health check..."
-        sleep 30
-
-        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $HEALTHCHECK_URL)
+        POD=$(kubectl get pods -l app=$IMAGE -o jsonpath="{.items[0].metadata.name}")
+        STATUS_CODE=$(kubectl exec $POD -- curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
         echo "Health check returned: $STATUS_CODE"
-
         if [ "$STATUS_CODE" -ne 200 ]; then
-          echo "Health check failed! Rolling back..."
-          kubectl rollout undo deployment/$IMAGE
-          kubectl rollout status deployment/$IMAGE
-          exit 1
+         echo "Health check failed! Rolling back..."
+         echo $IMAGE
+         kubectl rollout undo deployment/$IMAGE
+         kubectl rollout status deployment/$IMAGE
+         exit 1
         else
-          echo "Application is healthy"
+         echo "Application is healthy"
         fi
